// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		int greaterHalf = 0;
		int lessHalf = 0;
		
		for(int i = 0 ; i < nTimes ; i++){
		double random = Math.random();
	    if (random < 0.5){
			lessHalf ++;
		}else{
			greaterHalf ++;
		}
	}
	System.out.println("> 0.5: " + greaterHalf + " times");
	System.out.println("<= 0.5: " + lessHalf + " times");
	if(lessHalf > 0){
			double ratio = (double) greaterHalf / lessHalf;
			System.out.println("Ratio: " + ratio);
		}	
	}
}
